[package]
name = "walker"
version = "0.1.0"
authors = ["ryanc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.3.4"
walkdir = "2.3.1"
